import Head from 'next/head'
import {Inter} from 'next/font/google'
import Layout from "@/layout";
import Slider from "@/components/slider/Slider";
import About from "@/components/about/About";
import Skills from "@/components/skills/Skills";
import FeedBack from "@/components/feedBack/FeedBack";
import Portfolio from "@/components/portfolio/Portfolio";
import Contact from "@/components/contact/Contact";

const inter = Inter({subsets: ['latin']})

export default function Home() {
  return (
    <>
      <Head>
        <title>Abroudi</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Layout>
        <main className={`${inter.className}`}>
          <Slider/>
          <About/>
          <Skills/>
          <FeedBack/>
          <Portfolio/>
          <Contact/>
        </main>
      </Layout>
    </>
  )
}
